package com.testehan.ecommerce.common.entity.setting;

public enum SettingsNames {
    SITE_NAME,
    SITE_LOGO,
    COPYRIGHT,
    CURRENCY_ID,
    CURRENCY_SYMBOL,
    DECIMAL_POINT_TYPE,
    DECIMAL_DIGITS,
    MAIL_HOST,
    MAIL_FROM,
    SMTP_AUTH,
    SMTP_SECURED,
    MAIL_SENDER_NAME,
    ORDER_CONFIRMATION_CONTENT,
    MAIL_PORT,
    MAIL_USERNAME,
    MAIL_PASSWORD,
    CUSTOMER_VERIFY_SUBJECT,
    CUSTOMER_VERIFY_CONTENT,
    CURRENCY_SYMBOL_POSITION,
    THOUSANDS_POINT_TYPE,
    ORDER_CONFIRMATION_SUBJECT,
    PAYPAL_API_BASE_URL,
    PAYPAL_API_CLIENT_ID,
    PAYPAL_API_CLIENT_SECRET
}
